# Permalinks
#
permalink:           pretty
markdown:            kramdown

# Setup
title:               Keras CNN for Fashion MNIST
tagline:             'Image classification'
description:         'Classification of Fashion MNIST image data with a shallow CNN written in Keras.'
url:                 https://rmwenzel.com
baseurl:             /keras_cnn_fashion_mnist

# About/contact
author:
  name:              Ryan Wenzel
  url:               https://rmwenzel.com
  email:             rmwenzel@uw.edu

kramdown:
  parse_block_html: true

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-katex

